name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1
        sudo git clone --depth 1 --branch android-4.4.4_r2.0.1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7 /opt/toolchains/arm-eabi-4.7/
    - name: Building Kernel
      run: |
        make young2ve3g_hw00_defconfig
        make -j$(nproc --all)
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/zImage /home/runner/work/output/zImage
        find . -name "*.ko" -exec cp {} /home/runner/work/output/ \;
    - name: Uploading Output
      uses: actions/upload-artifact@v4
      with:
        name: zImage
        path: /home/runner/work/output/zImage
    - name: Uploading dt.img
      uses: actions/upload-artifact@v4
      with:
        name: dtb
        path: /home/runner/work/output/dtb
    - name: Uploading Modules
      uses: actions/upload-artifact@v4
      with:
        name: modules
        path: /home/runner/work/output/*.ko
